### ISSUE TITLE
Preserve items order in menu bar

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#2]
- [ ] Add persistence to items order in menu bar
- [ ] Allow user to configure items order in Preferences

**Comment by JayBrown** [comment]
This might not be a viable solution for SwiftBar, but there was a workaround that one user found for BitBar. The order that scripts are loaded in BitBar is apparently based on their inode number, which you can see with e.g. `stat -x foo`. The workaround is then to put the actual regular files of the scripts somewhere else, and only create symbolic links to them in the SwiftBar plugins folder, and create those symlinks in the order you want your plugins to be. Therefore the plugin behind the symlink with the lowest inode will be on the far right, and the plugin behind the symlink with the highest inode will be on the far left.

But I assume that it's possible to create a better solution eventually, because this is just a workaround.

(On the other hand, SwiftBar could just create a "secret plugins folder" somewhere in ~/Library, where it creates the symlinks in the right inode order, based on the order applied by the user in the GUI preferences.)

Another thing is to make a plugin preserve the actual _place_ in the menu bar. With BitBar, even when using tools like Bartender, plugins tend to lose the place you assigned them with CMD-click&drag. (But that's an issue for another time, I assume… and another topic.)

**Comment by edjusted** [comment]
I use Bartender to rearrange and remember my menu bar items, and Bartender also can't seem to save Swiftbar menu item positions.

According to the Bartender developer, he's thinking that Swiftbar items don't get loaded in the same order and/or don't have the same ID every time they load, so nothing can keep track of where they should go.

**Comment by melonamin** [comment]
>items don't get loaded in the same order

This is what I'd like to address in this issue

>don't have the same ID

I don't know enough about it and not sure what ID they're referring to, I need to research

**Comment by xilopaint** [comment]
Will this feature be included when the preferences redesign is done? This is a relevant issue for streaming plugins.

**Comment by zkarj735** [comment]
I was researching this exact problem hence found this issue. After some testing I can declare that the order is not based on anything fixed in the filesystem or anywhere else. I quit and restart SwiftBar four times and got four different orders of my four plugins!

The one behaviour I can repeat is to rename a script and it will move to the far left. Until you quit and restart at least.

**Comment by minamotorin** [comment]
[On BitBar](https://github.com/matryer/bitbar/issues/565#issuecomment-757243172), I preserve items order with defaults command: `% defaults write com.matryer.BitBar "NSStatusItem Preferred Position Item-something" 13`. But it (`% defaults write com.ameba.SwiftBar "NSStatusItem Preferred Position Item-something" 13`) doesn't work good with SwiftBar because `item-something` will change every loadings. I think this has something to do with “items don't get loaded in the same order” and “don't have the same ID”.
