### ISSUE TITLE
Swiftbar freezes on install

### ISSUE THREAD

**Issue by jdeweese1** [swiftbar/SwiftBar#24]
Hi,

I tried installing Swiftbar last night via hombrew.

After it installed I opened it, and it prompted me to select a folder. Out of habit, I thought that it wanted me to select a folder to install to, and I chose ~/Applications.

SwiftBar then disappeared, and my fans started spinning up. This also caused several commands in my terminal to be unresponsive, see attached.

I opened Activity Monitor, and killed Swiftbar, only to see that there were what looked like hundreds if not thousands of bash processes started, and one that said it was taking up 11 billion percent CPU.

I tried killing these processes to no avail in the terminal, as many terminal commands were now broken, yielding the below output:
```Bash
spaceship_exec_time_preexec_hook:2: fork failed: resource temporarily unavailable
zsh: fork failed: resource temporarily unavailable
precmd:1: fork failed: resource temporarily unavailable
```

To kill these processes, I had to restart my machine.

<img width="958" alt="Screen Shot 2020-11-26 at 1 27 19 AM" src="https://user-images.githubusercontent.com/32393906/100376009-604a8200-2fd4-11eb-9351-60020da9f1ca.png">

<img width="1072" alt="Screen Shot 2020-11-26 at 1 27 09 AM" src="https://user-images.githubusercontent.com/32393906/100376000-5d4f9180-2fd4-11eb-8c95-c0b9b1bf16d2.png">

Device:
15" 2018 MBP
2.6GHz 6 Core i7
16GB Ram

**Comment by melonamin** [comment]
> After it installed I opened it, and it prompted me to select a folder. Out of habit, I thought that it wanted me to select a folder to install to, and I chose ~/Applications.

Yes, this is a tricky part, SwiftBar is not user friendly at this step and we need to work on improving that.

What happened is quite scary, as soon as you set Plugin Folder SwiftBar recursively traverse it and try to launch each executable file it finds in a separate process. Since ~/Applications contains all applications installed on your Mac and each application is in fact a folder with a bunch of files in it... you can imagine why it froze your laptop.

I see two potential mitigation strategies here:
- make onboarding screen, explaining how to setup SwiftBar
- explicitly deny choosing ~/Applications
- give a warning when the user chose a folder with more than X number of files, i.e. potential mistake.

**Comment by JayBrown** [comment]
You can quickly get all app directories with NSAllApplicationsDirectory in NSAllDomainsMask, and outright ban those.

https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nsallapplicationsdirectory

**Comment by jdeweese1** [comment]
Thanks for the information. 

I tried reinstalling the application, but to no avail, as the settings file wasn't overwritten on install. 

To remedy I ran 
```Bash
$ defaults write com.ameba.Swiftbar PluginDirectory "/Users/jaroddeweese/.swiftbar"
```

**Comment by JayBrown** [comment]
Another option, to hedge it even further, would be to scan only the first level (i.e. root) of the user-selected plugin directory… in `find` terminology: `-mindepth 1` and `-maxdepth 1`. Then any nested files would be ignored, and only regular files with executable permissions at root level would be accepted by SwiftBar.

**Comment by melonamin** [comment]
> would be to scan only the first level (i.e. root) of the user-selected plugin directory

Not sure about that, I explicitly implemented recursive traverse of the plugin folder because I wanted to have subfolders there. I don't think that subfolders by itself are a problem, we just need safeguards.

> executable permissions 

By the way, about this one, SwiftBar will set the executable flag to any file it founds. I found cumbersome that in BitBar you need to add file and don't forget to set the -x flag and then reload plugins... So in SwiftBar as soon as new file appears in the plugins folder the executable permission is set and plugin loads automatically.

For this issue I suggest to leave it as it is for now and see if it cause any trouble in the future for new users.

**Comment by JayBrown** [comment]
The automatic `-x` flag is actually a good idea.

As for locations, you could ban:
* all applications directories (NSAllApplicationsDirectory)
* user library (`~/Library`)
* all root directories except subdirectories `~/*` `/Users/Shared/*` `/usr/local/SwiftBar`
* `~` itself
* `/Users/Shared` itself

thereby allowing only
* `/usr/local/SwiftBar`
* subdirectories in `/Users/Shared`
* subdirectories in `~` (without `~/Library`, `~/Applications` & `~/Developer/Applications`)

**Comment by dbyler** [comment]
I did something similar: on first launch I accidentally chose my Dropbox folder. When I launch SwiftBar, it appears in Activity Monitor (and it's churning ~20% CPU, not sure what it's doing) but nothing appears in my menu bar. I tried using jdeweese1's `defaults write com.ameba.SwiftBar...` solution but that didn't resolve the issue.

Is it possible to do a _complete_ uninstall?

**Comment by melonamin** [comment]
I think the easiest way to uninstall it completely is to use [AppCleaner](https://freemacsoft.net/appcleaner/) or something similar.

Or you can refer to the file list below:

<img width="693" alt="Screen Shot 2020-12-17 at 8 34 53 AM" src="https://user-images.githubusercontent.com/222100/102494511-beeaa500-4042-11eb-8936-b627641c15d5.png">
