### ISSUE TITLE
Move top level SwiftBar menu items to SwiftBar fly-out menu

### ISSUE THREAD

**Issue by quarterdeck** [swiftbar/SwiftBar#29]
What do people think about moving the following items into the SwiftBar dropdown menu?

- Last updated time
- Run in terminal
- Disable plugin

I think they're quite visually noisy and infrequently used.

**Comment by JayBrown** [comment]
I actually think their placement is fine.

I use the last-updated time quite often when troubleshooting/developing. The other three could theoretically go into yet another submenu, but not into the "SwiftBar" submenu, because that's the general submenu for the main app.

Or you could _hide_ the menu items, i.e. only the last-updated time is visible, but when the user presses [ALT], then a new menu item appears in its place, with a submenu that contains "Run in Terminal…", "Disable Plugin", and "About".

**Comment by JayBrown** [comment]
Or another idea: options to individualize scripts _from within_ the script. Below are examples for commands that would be placed at the top of the script, somewhere belong the shebang, but accounting for other "top items" like `shellcheck` etc., and would be "muted" by SwiftBar before the script executes, but applied by SwiftBar as settings, and these settings would only be valid for the individual plug-in.

`SB_NOSBICON` — do not display the SwiftBar icon
`SB_NOABOUT` — hide the "About" root menu item
`SB_NOTERMINAL` — hide the "Run in Terminal…" root menu item
`SB_NODISABLE` — hide the "Disable Plugin" root menu item
`SB_NOUTIME` — hide the last-update time in the root menu

**Comment by JayBrown** [comment]
To clarify how it works in Platypus.

When you execute `printf "QUITAPP\n"` in your shell script, it will quit the Platypus wrapper application.

So the above examples would probably be `printf "SB_NOABOUT\n"`, `printf "SB_QUIT\n"` etc.

**Comment by JayBrown** [comment]
^/^^ These would, however, break compatibility with the original BitBar app, so they should probably be commented out:

```
# SB_NOSBICON
# SB_QUIT
```

Don't know if such a thing woud be parseable, especially something like `# SB_QUIT`.

**Comment by JayBrown** [comment]
^ This might actually work, because we already have something similar, namely the `bitbar` tags, e.g.…

`# <bitbar.abouturl>https://github.com/JayBrown/Ping-Thing</bitbar.abouturl>`

…so we could add something like

`# <swiftbar.modifications>NOSBICON,NOABOUT,NOTERMINAL,NODISABLE</swiftbar.modifications>`

(However, that wouldn't cover direct commands in the script like "quit app" or "relaunch app".)

But that would be a neat way of modifying a plug-in's appearance, while sticking to an already established formula.

**Comment by melonamin** [comment]
Thanks for the idea and discussion, here is how I decided to implement it.

1. Introduced new optional plugin metadata modifiers:
```
# <swiftbar.hideAbout>true</swiftbar.hideAbout>
# <swiftbar.hideRunInTerminal>true</swiftbar.hideRunInTerminal>
# <swiftbar.hideLastUpdated>true</swiftbar.hideLastUpdated>
# <swiftbar.hideDisablePlugin>true</swiftbar.hideDisablePlugin>
# <swiftbar.hideSwiftBar>true</swiftbar.hideSwiftBar>
 ```

2. Option+Click will **show all items**

![SwiftBar](https://user-images.githubusercontent.com/222100/101261866-267e2780-3708-11eb-9042-a57ad0ac6c78.gif)


As for "quit app" or "relaunch app" actions please create a separate issue, if this is still relevant.
