### ISSUE TITLE
Shell parameters over-escaping

### ISSUE THREAD

**Issue by kdeldycke** [swiftbar/SwiftBar#308]
In the [`meta_package_manger.7h.py` plugin](https://github.com/matryer/xbar-plugins/blob/main/Dev/meta_package_manager.7h.py) I'm maintaining for the last 5 years, I'm trying to execute a `python3 -m pip` command.

Which works for `bash`, but not for `zsh` as you can see:

```shell-sesion
❯ bash
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.

bash-3.2$ mpm --version
bash: mpm: command not found

bash-3.2$ python3 -m pip install --upgrade meta-package-manager>=4.2.0

bash-3.2$ mpm --version
mpm, version 4.12.1
```

```shell-sesion
❯ zsh --version
zsh 5.8.1 (arm-apple-darwin21.3.0)

❯ python3 -m pip install --upgrade meta-package-manager>=4.2.0
zsh: 4.2.0 not found
```

The trick is to quote the last parameter or escape the angle-bracket within:

```shell-sesion
❯ python3 -m pip install --upgrade "meta-package-manager>=4.2.0"
(...)
Successfully installed meta-package-manager-4.12.1

❯ python3 -m pip install --upgrade meta-package-manager\>=4.2.0
(...)
Requirement already satisfied: meta-package-manager>=4.2.0
```

```shell-sesion
bash-3.2$ python3 -m pip install --upgrade "meta-package-manager>=4.2.0"
(...)
Requirement already satisfied: meta-package-manager>=4.2.0

bash-3.2$ python3 -m pip install --upgrade meta-package-manager\>=4.2.0
(...)
Requirement already satisfied: meta-package-manager>=4.2.0
```

These examples have the advantage of working for both `bash` and `zsh`.

Now I'd like to transpose that workaround in SwiftBar. But no amount of tweaking let me have one of this CLI executed as-is.

Here is a Python-based SwiftBar plugin exploring the possibilities:

```python
#!/usr/bin/env python3

print("Escape Test | dropdown=false")
print("---")

base_cmd = " | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade "

# Bare argument
print("Test 1" + base_cmd + "param5=meta-package-manager>=4.2.0")

# Quoted argument
print("Test 2" + base_cmd + "param5='meta-package-manager>=4.2.0'")
print("Test 3" + base_cmd + 'param5="meta-package-manager>=4.2.0"')

# Quote hacks
print("Test 4" + base_cmd + 'param5=\\"meta-package-manager>=4.2.0\\"')
print("Test 5" + base_cmd + "param5=\\'meta-package-manager>=4.2.0\\'")
print("Test 6" + base_cmd + 'param5=\\\\"meta-package-manager>=4.2.0\\\\"')
print("Test 7" + base_cmd + "param5=\\\\'meta-package-manager>=4.2.0\\\\'")

# Angle bracket hacks
print("Test 8" + base_cmd + "param5=meta-package-manager\>=4.2.0")
print("Test 9" + base_cmd + "param5=meta-package-manager\\>=4.2.0")
```

On execution, it returns:

```shell-session
❯ ./escape_test.1d.py
Escape Test | dropdown=false
---
Test 1 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=meta-package-manager>=4.2.0
Test 2 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5='meta-package-manager>=4.2.0'
Test 3 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5="meta-package-manager>=4.2.0"
Test 4 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=\"meta-package-manager>=4.2.0\"
Test 5 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=\'meta-package-manager>=4.2.0\'
Test 6 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=\\"meta-package-manager>=4.2.0\\"
Test 7 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=\\'meta-package-manager>=4.2.0\\'
Test 8 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=meta-package-manager\>=4.2.0
Test 9 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=meta-package-manager\>=4.2.0
```

Which renders into SwiftBar as:

<img width="225" alt="Screen Shot 2022-04-13 at 15 10 08" src="https://user-images.githubusercontent.com/159718/163167916-48d00817-1a08-4152-848b-2059e5e43065.png">

Some of these 9 tests properly executes my command, others fails:

❌ Tests `#1`, `#2` and `#3` runs:
```shell-session
❯ export SWIFTBAR_PLUGIN_CACHE_PATH='/Users/kde/Library/Caches/com.ameba.SwiftBar/Plugins/escape_test.1d.py' SWIFTBAR='1' SWIFTBAR_PLUGINS_PATH='' SWIFTBAR_PLUGIN_DATA_PATH='/Users/kde/Library/Application Support/SwiftBar/Plugins/escape_test.1d.py' OS_VERSION_PATCH='1' OS_VERSION_MINOR='3' OS_VERSION_MAJOR='12' SWIFTBAR_VERSION='1.4.3' SWIFTBAR_LAUNCH_TIME='2022-04-06T14:20:14+04:00' OS_LAST_SLEEP_TIME='2022-04-10T10:29:57+04:00' OS_APPEARANCE='Light' SWIFTBAR_BUILD='422' SWIFTBAR_PLUGIN_PATH='/Users/kde/dotfiles/dotfiles/Library/Application Support/xbar/plugins/escape_test.1d.py' OS_LAST_WAKE_TIME='2022-04-10T14:48:52+04:00';python3 -m pip install --upgrade meta-package-manager>=4.2.0
zsh: 4.2.0 not found
```

✅ Tests `#4` succeeded:
```shell-session
❯ export OS_VERSION_PATCH='1' SWIFTBAR_PLUGINS_PATH='' OS_LAST_WAKE_TIME='2022-04-10T14:48:52+04:00' OS_VERSION_MAJOR='12' SWIFTBAR_VERSION='1.4.3' SWIFTBAR_BUILD='422' OS_VERSION_MINOR='3' OS_APPEARANCE='Light' SWIFTBAR_PLUGIN_CACHE_PATH='/Users/kde/Library/Caches/com.ameba.SwiftBar/Plugins/escape_test.1d.py' OS_LAST_SLEEP_TIME='2022-04-10T10:29:57+04:00' SWIFTBAR='1' SWIFTBAR_PLUGIN_PATH='/Users/kde/dotfiles/dotfiles/Library/Application Support/xbar/plugins/escape_test.1d.py' SWIFTBAR_LAUNCH_TIME='2022-04-06T14:20:14+04:00' SWIFTBAR_PLUGIN_DATA_PATH='/Users/kde/Library/Application Support/SwiftBar/Plugins/escape_test.1d.py';python3 -m pip install --upgrade "meta-package-manager>=4.2.0"
(...)
Successfully installed meta-package-manager-4.12.1
```

❌ Tests `#7` runs:
```shell-session
❯ export OS_VERSION_MINOR='3' SWIFTBAR_PLUGIN_DATA_PATH='/Users/kde/Library/Application Support/SwiftBar/Plugins/escape_test.1d.py' SWIFTBAR_LAUNCH_TIME='2022-04-06T14:20:14+04:00' SWIFTBAR='1' SWIFTBAR_BUILD='422' OS_VERSION_PATCH='1' OS_APPEARANCE='Light' SWIFTBAR_PLUGIN_CACHE_PATH='/Users/kde/Library/Caches/com.ameba.SwiftBar/Plugins/escape_test.1d.py' OS_LAST_WAKE_TIME='2022-04-10T14:48:52+04:00' OS_LAST_SLEEP_TIME='2022-04-10T10:29:57+04:00' SWIFTBAR_VERSION='1.4.3' SWIFTBAR_PLUGIN_PATH='/Users/kde/dotfiles/dotfiles/Library/Application Support/xbar/plugins/escape_test.1d.py' SWIFTBAR_PLUGINS_PATH='' OS_VERSION_MAJOR='12';python3 -m pip install --upgrade \'meta-package-manager>=4.2.0\'
zsh: 4.2.0' not found
```

❌ Tests `#5`, `#6`, `#8` and `#9` don't work at all and fails to launch a terminal.

Looking at these examples, it seems there is something inconsistent in the way xbar is parsing parameters, handling outer quotes and/or over-escaping special characters.

Here is my environment:
* xbar 2.1.7-beta
* macOS Monterey 12.3.1
* zsh 5.8.1 (arm-apple-darwin21.3.0)
* GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
* Python 3.9.12

For the record, I tested the [same test suite on xbar](https://github.com/matryer/xbar/issues/831) but the results are completely different.

**Comment by melonamin** [comment]
Hey @kdeldycke, thanks for such a thorough issues description.

Let me try to explain what is hapening under the hood.

First step, parse this thing:

`Test 1 | terminal=true shell=python3 param1=-m param2=pip param3=install param4=--upgrade param5=meta-package-manager>=4.2.0`

1. Everething after `|` is a parameters string.
2. Everything before `=` is parameter name, tabs and spaces are trimmed
3. Everything after `=` and before a `space` is parameter value
4. If you want a parameter value to contain a space, then you can quote it. In this case 3. works differently: everything within quotes after the `=` is a value. The quotes are not considered to be a part of the value and **being stripped**

That's why the internal shell command, before it is run will look like this:
- Test 1-3 - `python3 -m pip install --upgrade meta-package-manager>=4.2.0`
- Test 4 - `... --upgrade \"meta-package-manager>=4.2.0\"`
- Test 5 - `...  --upgrade \'meta-package-manager>=4.2.0\'`
- Test 6 - `...  --upgrade \\"meta-package-manager>=4.2.0\\"`
- Test 7 - `...  --upgrade \\'meta-package-manager>=4.2.0\\'`
- Test 8-9 - `... --upgrade meta-package-manager\>=4.2.0`

Second step, execute the the shell command we've formed on the previous step. ~Unfortunately~ We have two options:
- run in background
- run in terminal

Run in background is more or less straightforward(not really), and doesn't mess with the escaping any further, run in terminal on the other hand is going through Apple Script. To make things a bit more complicated, there two, slightly different Apple Script srcipts, one for Terminal and one for iTerm. 

```swift
        switch PreferencesStore.shared.terminal {
        case .Terminal:
            appleScript = """
            tell application "Terminal"
                activate
                tell application "System Events" to keystroke "t" using {command down}
                delay 0.2
                do script "\(runInTerminalScript)" in front window
                activate
            end tell
            """
        case .iTerm:
            appleScript = """
            tell application "iTerm"
                activate
                try
                    select first window
                    set onlywindow to false
                on error
                    create window with default profile
                    select first window
                    set onlywindow to true
                end try
                tell the first window
                    if onlywindow is false then
                        create tab with default profile
                    end if
                    tell current session to write text "\(runInTerminalScript)"
                end tell
            end tell
            """
        }
```

Because of that, as far as I can tell here is what we have:
- Test 1-3 will fail with `terminal=true` and  `terminal=false`, because the string is not escaped after SwiftBar strips the quotation
- Test 4 works with `terminal=true`, but will fail with `terminal=false`. `... --upgrade \"meta-package-manager>=4.2.0\"` becomes `... --upgrade "meta-package-manager>=4.2.0"` after going though Apple Script, if this goes directly to zsh it will fail
- Test 5-6 fail to run with `terminal=true` because the escaping pattern causes a syntax error in Apple Script. These will not work with `terminal=false` either because zsh will not be happy with `\`
- Test 7 runs because the `\` is escaped with another `\` and Apple Script doesn't fail, but the end result is the same - zsh is not happy with `\`
- Test 8-9 fail to run with `terminal=true` due to escaping issue in Apple Script, but they will run with `terminal=false` because zsh is happy to run this `... --upgrade "meta-package-manager\>=4.2.0`

All in all Test 4 is OK for interactive run and 8-9 for background.

I haven't time to thorougly test this, but I almost sure everything above is correct. Didn't look into bash instead zsh either, but I hope it helps.

**Comment by melonamin** [comment]
@kdeldycke hey, do you have any suggestions on how to make it easier for you to use?

**Comment by kdeldycke** [comment]
Might be related to: https://github.com/swiftbar/SwiftBar/issues/366
