### ISSUE TITLE
Naming plugins without extension

### ISSUE THREAD

**Issue by chew-z** [swiftbar/SwiftBar#314]
I have built my own binary plugin named `feuvol.3m` and it didn't get refreshed every 3 minutes. Changed plugin name to `feuvol.3m.gobinary` and it gets refreshed OK. 

But binaries usually do not have extension so this is confusing a bit.

**Comment by melonamin** [comment]
In my own usage I do one of the two:
* Follow the 3 part naming scheme, usually like this: `plugin.5m.swiftbar`
* Or use the [Cron Schedule](https://github.com/swiftbar/SwiftBar#metadata-for-binary-plugins), since binary plugins [support metadata](https://github.com/swiftbar/SwiftBar#metadata-for-binary-plugins) as well

**Comment by chew-z** [comment]
Sure...

I have been migrating from xbar and this is one of few oddities, where I had to guess. It is also not so clear from reading README so perhaps worth clarification for other users...
