### ISSUE TITLE
Swiftbar icon disappearing

### ISSUE THREAD

**Issue by ifuchs** [swiftbar/SwiftBar#325]
I am finding that the Swiftbar menu item itself is periodically disappearing from my menubar. I am wondering if there is a way for Swiftbar to use a small Icon like most other items rather than the word "Swiftbar"?

**Comment by melonamin** [comment]
Hey @ifuchs.

SwiftBar is designed to be invisible, the only time it shows "SwiftBar" in the menubar is when you don't have any plugins installed\enabled.

When you have a plugin, you control how it looks(that's the point of the app) and you have access to all features which are available in "default" "SwiftBar" menu item.

So overall this is by design. Maybe if you elaborate your use case a bit I could offer you a solution.

**Comment by ifuchs** [comment]
This is probably a case of my not understanding how Swiftbar is used but I downloaded a plugin and enabled it (Yahoo stock ticker).  It showed stock prices in the menubar. Then I quit Swiftbar and restarted it. It  with disappeared from the menubar along with the plugin output.. Also, even when no plugins are enabled, the swiftbar item is not visible unless there is room on the menubar (as in Finder). If an app is running, it won’t be there. That is probably not an issue if it is only there to configure plugins but I’m still unclear as to why my plugin (and swiftbar) no longer show up or how to get even the swiftbar item back (e.g., to enable or disable plugins).

**Comment by melonamin** [comment]
> how Swiftbar is used

Most of the people I know used it to run their custom plugins, some of the people I know use plugins developed by others. Thirdparty plugins are tricky, because it is up to its author to keep it working and the issues you most likely related to plugin itself.

> Also, even when no plugins are enabled, the swiftbar item is not visible unless there is room on the menubar

This is a feature of macOS it will hide left most menubar items if you are out of space in the menu bar, app menu has a priority.

> I’m still unclear as to why my plugin (and swiftbar) no longer show up or how to get the swiftbar item back

This is either a bug in SwiftBar(not likely, I would hear about it a lot from users) or bug or feature in plugin. The thing is that a plugin can return "empty output" and in this case SwiftBar will show nothing. It could be a feture for some plugins, for example GitHub Notifications plugin will appear in the menubar only if there is a notification to show.

**Comment by ifuchs** [comment]
OK, understood. I will try some other plug-ins to see if the problem I’m
seeing carries over. At this point, since the Swiftbar menu is not
accessible, is the best course of action to delete the plug-in from the
folder so that the menu will come back?

**Comment by melonamin** [comment]
Yes, either delete\rename plugin or disable it using [URL Scheme](https://github.com/swiftbar/SwiftBar#url-scheme)

**Comment by ifuchs** [comment]
One of the ways you mention in the docs to add plugins written by others is to use the “Get Plugins” menu item. However, since the Swiftbar menu is only visible for a moment after I start Swiftbar, how does one bring it back to use it?

**Comment by melonamin** [comment]
Like this, most of the plugins will include standard SwiftBar menu item. If you don't see it hold Option and click to reveal it
<img width="409" alt="CleanShot 2022-07-13 at 22 01 08@2x" src="https://user-images.githubusercontent.com/222100/178881122-3db4f276-c22d-43d5-8ebd-e3c188ddccbc.png">
.
