### ISSUE TITLE
SwiftBar lists non-executable files as executable scripts.

### ISSUE THREAD

**Issue by sirgatez** [swiftbar/SwiftBar#379]
**Describe the bug**
For example I have BitBar scripts that save configuration data in a file alongside the script itself. The script is marked +x but the configuration files are not. However when pointing SwiftBar to the plugin folder it identifies these configuration files as executable and displays them in the menubar.

**To Reproduce**
Place file in plugins folder that is not executable.

**Expected behavior**
Non executable files should not be listed, as they do not produce any output.

**Screenshots**
![Screenshot 2023-05-17 at 3 14 54 PM](https://github.com/swiftbar/SwiftBar/assets/491513/39d4a382-1f12-48e6-a499-95785620d970)

**Environment:**
 - macOS version: 13.3.1
 - SwiftBar version: 1.4.4 (461)

**Plugin Example:**
Applies to all non executable files.

**Additional Context:**
I can disable the files from the SwiftBar menu and the files will no longer appear in the menubar.

- [ ] I don't run Bartender/Dozer/etc. or tested the issue without it running
I use Bartender, this issue is not related to Bartender.

**Comment by melonamin** [comment]
Hi @sirgatez,

> identifies these configuration files as executable and displays them in the menubar. 

SwiftBar actually makes every file in the plugin folder executable, this was added way back in one of the first versions, because users were having issues. I don't think I want to change this.

SwiftBar has two mechanisms to mark files\folders like "not plugins":
* make file or folder hidden
* .swiftbarignore #358 (this is an upcoming feature)

Additionnaly SwiftBar exposes these two env variables, that might be handy:
* SWIFTBAR_PLUGIN_CACHE_PATH - The cache to data folder, individual per plugin
* SWIFTBAR_PLUGIN_DATA_PATH	- The path to data folder, individual per plugin
