### ISSUE TITLE
Set environment properties

### ISSUE THREAD

**Issue by matopeto** [swiftbar/SwiftBar#50]
Hi

Bitbar sets `BitBar=1` env property so script can determine if it is launched from BitBar or not

Please add this env property for compatibility reason

And also please add `SwiftBar=1` so scripts can determine when they are running from SwiftBar and can cange some behaviour

not released BitBar also sets `BitBarVersion` env property with current program version (see: https://github.com/matryer/bitbar/pull/359/), please add `SwiftBarVersion` env property with current SwiftBar version, co plugin can determine and use new feature if it is running on new version and not use when not.

**Comment by melonamin** [comment]
I've added:
* SwiftBar = 1
* SwiftBarVersion = <current version, i.e. 1.0.2>
* SwiftBarBuild = <current build number, i.e. 145>

Here is another thing I want to brainstorm, some plugins may need access to secrets, like AWS key or something like that. I never liked the idea of putting the secrets into plugin script itself, so instead we can:

* Inject secrets from a file provided by user
* or provide a UI to edit env\secrets and store it in the keychain on per plugin basis but this seems like an overkill

**Comment by matopeto** [comment]
Thank you for add env properties

To other thing: I think that SwiftBar shouldn't store or provide secrets or API for it and provide to plugins in any way. It is plugin/script responsibility how to configure for specific task. If you must edit script for adding some key, you can edit it and load from other place (file, keyehain) if you want. If it is not secure, contact author of the script to provide bettery way.

**Comment by JayBrown** [comment]
(1) more environment variables:

* SystemMajorVersion = (e.g.) `10`
* SystemMinorVersion = (e.g.) `15`
* SystemFixVersion = (e.g.) `7`

(2) I like the idea of providing secrets, OAuth tokens etc. for individual plug-ins from individual files

* the files would need a fixed naming scheme and location… could be a sub-folder in the SwiftBar plug-ins folder
* it gets a bit more complex with the naming scheme and the keys themselves: so if a plug-in is called `myPlugIn.30s.sh`, the secrets file would (for example) be `sh.30s.myPlugIn.secrets`, here following the reverse URL scheme
* However, what if you need several secret keys, e.g. username and password? Would that mean two files, `sh.30s.myPlugIn.secrets.username` and `sh.30s.myPlugIn.secrets.password`? Or one file with several keys using a certain format, e.g. yaml?

(3a) As for the keychain issue: if a plug-in needs a secret or key or password etc. in the keychain, you can easily do that from within the plug-in with the `security` command, e.g. create a new keychain via osascript with admin privileges at first run, then populate it with keys/secrets the user has to input (also via osascript prompt)

(3b) But I wouldn't be against using a SwiftBar in-app solution, but that would be quite complex, because SwiftBar would have to handle keychain creation, keychain item creation, while supplying a specific keychain item naming scheme… still, the script itself would have to handle the user-secrets input first, e.g. because a username/password combination would need to be tested first, and then the script already has the relevant data, i.e. you're already halfway there, and all you'd need to do is write to a keychain with `security`.

**Comment by matopeto** [comment]
@JayBrown i think there is no need for System* variables, Your plugin can call `sw_vers` command and determine system version

Also to providing secrets, I still think that if you or plugin needs some secrets, its plugin and/or user responsibility to load secrets. not Swiftbar.

**Comment by JayBrown** [comment]
Why not? Less commands to run if SwiftBar provides OS version numbers, i.e. faster & more responsive scripts.

**Comment by melonamin** [comment]
I see no issues in having more information in environment variables while it keeps the code nice and simple. I've added OS_VERSION.
