### ISSUE TITLE
Custom baseline offset

### ISSUE THREAD

**Issue by jmjordan** [swiftbar/SwiftBar#85]
If you increase the font size for the title then the text is not vertically aligned in the menu bar. Adjusting the baseline offset of the text can fix the problem. I propose either 1) calculate what the offset should be when the text is created or 2) allow user to specify a custom baseline offset in their script `Text | size=18 baselineoffset=-2`. I'm happy to implement this if it is approved.

<img width="236" alt="Screen Shot 2020-12-14 at 8 27 51 PM" src="https://user-images.githubusercontent.com/210460/102171224-e1b26900-3e4a-11eb-95ae-d0b55c03eaa5.png">

**Comment by melonamin** [comment]
I would prefer to have an automatic calculation, if it is possible. I think the only thing user would want is to center the text, in this case we should do it rather than giving an option.


Not directly related, but I have another ugly piece of code with a bunch of magic numbers we should fix one day:

```
class ImageAttachmentCell: NSTextAttachmentCell {
    override func cellBaselineOffset() -> NSPoint {
        var baseline = super.cellBaselineOffset()
        baseline.y = baseline.y - 3 - (image!.size.height - 16)/2
        return baseline
    }
}
```

I'd be happy if take over the implementation.
